version: "3"
services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    image: islasgeci
    container_name: islasgeci-app
    ports: 
      - 8010:80
    volumes: 
      - ./:/var/www/html/